### ISSUE TITLE
Extra Configurability

### ISSUE THREAD

**Issue by aam-git** [nenadpnc/cl-editor#46]
Nice work on this plugin. I was using quill editor before this (stopped due to security bulletin that wasn't patched), I added some extra configurability to things like colours on my local quill install, would you be happy for me to push some extra configuration changes to do the same for this plugin?

**Comment by nenadpnc** [comment]
I'm always open to suggestions, but bare in mind that this lib is meant to be as lightweight as possible.
Library is easily extendible, so any extra configuration should be implemented in the consuming app.
Otherwise, it can spin easily into huge library and weight couple of hundreds of kilobytes, like quill, tinymce and co.

**Comment by aam-git** [comment]
No problem, most of the changes I would do would be config going in (just like you have done) so very minimal changes.

**Comment by aam-git** [comment]
Just pushed the colour configurator, if i think of any other tiny tweaks will let you know.  Nice work again :)
